[package]
name = "demotui"
edition.workspace = true

[dependencies]
log = { workspace = true }
env_logger = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yml.workspace = true

# CLI
clap.workspace = true
clap_complete.workspace = true

# TUI
tokio = { workspace = true, optional = true }
crossterm = { workspace = true, optional = true }
ratatui = { workspace = true, optional = true }
futures-lite = { workspace = true, optional = true }


[features]
customized-theme = ["tui", "ratatui/serde"]
migration_v0_2_3 = []
tui = ["dep:ratatui", "dep:crossterm", "dep:tokio", "dep:futures-lite"]

default = ["customized-theme"]
