[package]
name = "demotui"
edition.workspace = true

[dependencies]
log = { workspace = true }
env_logger = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }


# TUI
tokio = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
futures-lite = { workspace = true }


[features]
# tui = [
#   "dep:ratatui",
#   "dep:crossterm",
#   "dep:tokio",
#   "dep:futures-lite",
#   "dep:derive_more",
#   "dep:strum",
# ]

# default = ["tui"]
