[package]
name = "demotui-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
demotui-shared = {path = "../demotui-shared"}

anyhow = {workspace = true}
tokio = {workspace = true}
log = { workspace = true }
env_logger = { workspace = true }